name: Linting & Formatting

on:
  push:
    branches: [main]
  pull_request:

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@master
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install linter
        run: luarocks install luacheck

      - name: Lint
        run: luacheck lua

      #  TODO: this is not working :/
      #- name: Install formatter
        #run: luarocks install --server=https://luarocks.org/dev luaformatter

      #- name: Check formatting
        #run: lua-format -c .lua-format.yaml --check --verbose lua/**/*

